pipeline:
    name: deploy_nginx_canary
    identifier: deploy_nginx_canary
    allowStageExecutions: false
    projectIdentifier: johannesbootcamp
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: deploy_nginx_to_dev
              identifier: deploy_nginx_to_dev
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: nginx
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables:
                                  - name: mySecret
                                    type: Secret
                                    value: mysecret
                              manifests:
                                  - manifest:
                                        identifier: nginx_yaml
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: account.EliGit
                                                    gitFetchType: Branch
                                                    paths:
                                                        - templates/app-deployment.yml
                                                        - templates/namespace.yml
                                                    repoName: ngfundamentals
                                                    branch: main
                                            skipResourceVersioning: false
                                  - manifest:
                                        identifier: nginx_values
                                        type: Values
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: account.EliGit
                                                    gitFetchType: Branch
                                                    paths:
                                                        - values.yml
                                                    repoName: ngfundamentals
                                                    branch: main
                              artifacts:
                                  primary:
                                      spec:
                                          connectorRef: account.bootcampdockerhub
                                          imagePath: library/nginx
                                          tag: <+input>
                                      type: DockerRegistry
                  infrastructure:
                      environmentRef: dev
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: account.bootcampgkecluster
                              namespace: internalbootcamp-johannes
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: K8sCanaryDeploy
                                name: Canary Deployment
                                identifier: Canary_Deployment
                                spec:
                                    skipDryRun: true
                                    instanceSelection:
                                        spec:
                                            percentage: 40
                                        type: Percentage
                                timeout: 10m
                                failureStrategies: []
                          - step:
                                type: Verify
                                name: verify
                                identifier: verify
                                spec:
                                    type: Canary
                                    spec:
                                        sensitivity: MEDIUM
                                        duration: 15m
                                        deploymentTag: <+serviceConfig.artifacts.primary.tag>
                                timeout: 2h
                                failureStrategies:
                                    - onFailure:
                                          errors:
                                              - Verification
                                          action:
                                              type: ManualIntervention
                                              spec:
                                                  timeout: 2h
                                                  onTimeout:
                                                      action:
                                                          type: StageRollback
                                    - onFailure:
                                          errors:
                                              - Unknown
                                          action:
                                              type: ManualIntervention
                                              spec:
                                                  timeout: 2h
                                                  onTimeout:
                                                      action:
                                                          type: Ignore
                          - step:
                                type: K8sCanaryDelete
                                name: Canary Delete
                                identifier: Canary_Delete
                                spec:
                                    skipDryRun: false
                                timeout: 10m
                          - step:
                                type: ShellScript
                                name: magic sauce
                                identifier: magic_sauce
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: ps -aux
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
